# Generated by Django 2.1.7 on 2019-08-09 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dropper', '0002_auto_20190306_0521'),
    ]

    operations = [
        migrations.CreateModel(
            name='DropRetrieval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('was_successful', models.BooleanField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='drop',
            name='last_retrieved_on',
        ),
        migrations.AddField(
            model_name='drop',
            name='expires_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drop',
            name='rejection_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drop',
            name='retrieval_limit',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='dropretrieval',
            name='drop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retrievals', to='dropper.Drop'),
        ),
    ]
