# Generated by Django 2.1.7 on 2019-08-22 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropper', '0003_auto_20190809_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='drop',
            name='password',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='drop',
            name='text',
            field=models.BinaryField(),
        ),
    ]
