# Generated by Django 2.1.7 on 2019-10-27 04:29

from django.db import migrations, models
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dropper', '0004_auto_20190822_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drop',
            name='expires_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drop',
            name='password',
            field=fernet_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drop',
            name='text',
            field=fernet_fields.fields.EncryptedTextField(),
        ),
    ]
